apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- pv-wordpress-mysql.yaml
- pvc-mysql.yaml
- pvc-wordpress.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- wordpress-deployment.yaml
- wordpress-service.yaml
- wordpress-nodeport.yaml